backend:
  name: git-gateway
  branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://codestitch.app/frontend/images/logo.png

# media_folder: "public/assets/images/blog"
# public_folder: "/assets/images/blog"
media_folder: "public/assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "titre", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Auteur", name: "auteur", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Image principale", name: "image", widget: "image" }
      - { label: "Légende image", name: "légende", widget: "string" }
      - { label: "Corps", name: "corps", widget: "markdown" }
